name: market-ai-web

services:
  marker-frontend:
    container_name: marker-frontend
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - '80'

networks:
  default:
    external: true
    name: game-network
