name: stack-market

services:
  redis-market:
    container_name: redis-market
    image: redis:8.4.0-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass Data_Redis_p6379
    volumes:
      - redis-market:/data

  timescaledb-market:
    container_name: timescaledb-market
    image: timescale/timescaledb:latest-pg18
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketaidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5436:5432'
    volumes:
      - timescaledb-market:/var/lib/postgresql/data
    command: ['-c', 'max_connections=200']

volumes:
  timescaledb-market:
  redis-market:

networks:
  default:
    name: market-network
